# Generated by Django 3.1.4 on 2021-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=200)),
                ('purchased', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
